---
name: Merge

'on':
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  validate-build-publish:
    name: Validate, Build, Publish
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Auth GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_DEV_DRM_SA_KEY }}'
          export_environment_variables: false

      - name: Configure npm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          npm config set update-notifier false
          npm config set audit false
          npm config set fund false
          npm run auth

      - name: Set SNAPSHOT version
        if: ${{ startsWith(github.ref, 'refs/heads') }}
        run: sed -i "s/0.0.1-snapshot.1/0.0.1-snapshot.$(git log -1 --format=%ct)/" package.json

      - name: Set RELEASE version
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: sed -i "s/0.0.1-snapshot.1/${GITHUB_REF_NAME#v}/" package.json

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Lint source code
        run: |
          npm run lint

      - name: Run build
        run: |
          npm run build

      - name: Run unit tests
        run: |
          npm test

      - name: Publish npm
        run: |
          npm publish
